baseURL = 'https://kmseunh.github.io/'
author = "Kim Seunghyun"
copyright = "Copyright © 2023, Kim Seunghyun and the lee.so; all rights reserved."
paginate = 5
languageCode = 'en-us'
DefaultContentLanguage = "en-us"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
title = 'DevHvun'
theme = "paper"

[params]
  color = 'linen'

  # header social icons
  github = 'kmseunh'
  linkedin = 'seunghyun-kim-250b562a6'
  rss = true

  # home page profile
  avatar = 'https://i.pinimg.com/originals/d3/03/96/d303960c44b99e5b86d361890a53cb9c.png'
  name = '1020'
  bio = 'Just Wanna Dev'

  # giscus 설정
  [params.giscus]
    repo = "kmseunh/kmseunh.github.io"
    repoId = "R_kgDOKefbLg"
    category = "Comments"
    categoryId = "DIC_kwDOKefbLs4Cgyq5"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "transparent_dark"
    lang = "ko"
    loading = "anonymous"

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = false                       # show monochrome dark mode icon
  math = true                               # enable KaTeX math typesetting globally

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "https://thundering-ursinia-ede.notion.site/62c63b5726ac4e269be8c08e97d6e0eb?pvs=4"
    weight = 10
  [[menu.main]]
    identifier = "series"
    name = "Series"
    url = "/series/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30

[taxonomies]
  category = "categories"
  tag = "tags"
  serie = "series"

[privacy]

  # [privacy.instagram]
  #  disabled = false
  #  simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

# [services]

  # [services.instagram]
  #   disableInlineCSS = true

# robots.txt
enableRobotsTXT = true

# sitemap 생성
[sitemap]
# always, hourly daily, weekly, monthly, yearly, never
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5